#### Keras  Tutorial
Whenever we work with machine learning algorithms that use a stochastic process (e.g. random numbers), it is a good idea to set the random number seed.

In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np
import pandas as pd
import seaborn as sns
from keras.utils.np_utils import to_categorical
from keras.utils import np_utils
from sklearn.model_selection import train_test_split
# fix random seed for reproducibility
np.random.seed(7)

Using TensorFlow backend.
/Users/nanaakwasiabayieboateng/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


#### 1.  Load Data

In [3]:


# load pima indians dataset
#dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")


# load pima indians dataset
dataset=pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data", delimiter=",")

#dataset=np.loadtxt("http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data", delimiter=",")

dataset.columns=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'] 

dataset.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     1    85    66    29     0  26.6  0.351   31      0
1     8   183    64     0     0  23.3  0.672   32      1
2     1    89    66    23    94  28.1  0.167   21      0
3     0   137    40    35   168  43.1  2.288   33      1
4     5   116    74     0     0  25.6  0.201   30      0

In [3]:


# load pima indians dataset
#dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")


# load pima indians dataset
dataset=pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data", delimiter=",")

#dataset=np.loadtxt("http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data", delimiter=",")

dataset.columns=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'] 

dataset.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     1    85    66    29     0  26.6  0.351   31      0
1     8   183    64     0     0  23.3  0.672   32      1
2     1    89    66    23    94  28.1  0.167   21      0
3     0   137    40    35   168  43.1  2.288   33      1
4     5   116    74     0     0  25.6  0.201   30      0



Download the Pima Indian dataset from the UCI Machine Learning repository.


In [2]:

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataset = pd.read_csv(url, names=names)
print(dataset.shape)

(768, 9)


In [8]:
dataset.head()


preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [9]:
dataset.describe()

preg        plas        pres        skin        test        mass  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

             pedi         age       class  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [54]:
#sns.pairplot(dataset, hue='class');
sns.pairplot(dataset);

In [32]:
# split into input (X) and output (Y) variables
X = dataset.iloc[:,0:8]
Y = dataset.iloc[:,8]

#convert data from panda dataframe to numpy ndarray.
X=X.values
#Y=Y.values
X[0:4,:]


array([[  6.00000000e+00,   1.48000000e+02,   7.20000000e+01,
          3.50000000e+01,   0.00000000e+00,   3.36000000e+01,
          6.27000000e-01,   5.00000000e+01],
       [  1.00000000e+00,   8.50000000e+01,   6.60000000e+01,
          2.90000000e+01,   0.00000000e+00,   2.66000000e+01,
          3.51000000e-01,   3.10000000e+01],
       [  8.00000000e+00,   1.83000000e+02,   6.40000000e+01,
          0.00000000e+00,   0.00000000e+00,   2.33000000e+01,
          6.72000000e-01,   3.20000000e+01],
       [  1.00000000e+00,   8.90000000e+01,   6.60000000e+01,
          2.30000000e+01,   9.40000000e+01,   2.81000000e+01,
          1.67000000e-01,   2.10000000e+01]])

In [33]:
#dataset["class"]

Y.head()

0    1
1    0
2    1
3    0
4    1
Name: class, dtype: int64

In [ ]:
#Equivalently
numpyMatrix = dataset.as_matrix()

**Converts a class vector (integers) to binary class matrix.**

In [34]:
#Y=keras.utils.to_categorical(Y, num_classes=2)
Y_cat=np_utils.to_categorical(Y, num_classes=2)
print(Y_cat)

[[ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 ..., 
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]]


#### Split data into training and test

In [46]:
np.random.seed(148)

seed =148

validation_size = 0.20

X_train, X_validation, Y_train, Y_validation = train_test_split(X, Y, test_size=validation_size, random_state=seed)

X_train
X_validation

array([[  4.00000000e+00,   8.40000000e+01,   9.00000000e+01, ...,
          3.95000000e+01,   1.59000000e-01,   2.50000000e+01],
       [  4.00000000e+00,   9.70000000e+01,   6.00000000e+01, ...,
          2.82000000e+01,   4.43000000e-01,   2.20000000e+01],
       [  4.00000000e+00,   1.03000000e+02,   6.00000000e+01, ...,
          2.40000000e+01,   9.66000000e-01,   3.30000000e+01],
       ..., 
       [  9.00000000e+00,   1.45000000e+02,   8.80000000e+01, ...,
          3.03000000e+01,   7.71000000e-01,   5.30000000e+01],
       [  1.10000000e+01,   1.03000000e+02,   6.80000000e+01, ...,
          4.62000000e+01,   1.26000000e-01,   4.20000000e+01],
       [  7.00000000e+00,   1.06000000e+02,   9.20000000e+01, ...,
          2.27000000e+01,   2.35000000e-01,   4.80000000e+01]])

#### 2. Define Model

Models in Keras are defined as a sequence of layers.

We create a Sequential model and add layers one at a time until we are happy with our network topology.

The first thing to get right is to ensure the input layer has the right number of inputs. This can be specified when creating the first layer with the **input_dim** argument and setting it to 8 for the 8 input variables.
How do we know the number of layers and their types?

This is a very hard question. There are heuristics that we can use and often the best network structure is found through a process of trial and error experimentation. Generally, you need a network large enough to capture the structure of the problem if that helps at all.

In this example, we will use a fully-connected network structure with three layers.

Fully connected layers are defined using the Dense class. We can specify the number of neurons in the layer as the first argument, the initialization method as the second argument as **init** and specify the activation function using the **activation** argument.

In this case, we initialize the network weights to a small random number generated from a uniform distribution (‘**uniform**‘), in this case between 0 and 0.05 because that is the default uniform weight initialization in Keras. Another traditional alternative would be ‘**normal**’ for small random numbers generated from a Gaussian distribution.

We will use the rectifier (‘**relu**‘) activation function on the first two layers and the sigmoid function in the output layer. It used to be the case that sigmoid and tanh activation functions were preferred for all layers. These days, better performance is achieved using the rectifier activation function. We use a sigmoid on the output layer to ensure our network output is between 0 and 1 and easy to map to either a probability of class 1 or snap to a hard classification of either class with a default threshold of 0.5.

We can piece it all together by adding each layer. The first layer has 12 neurons and expects 8 input variables. The second hidden layer has 8 neurons and finally, the output layer has 1 neuron to predict the class (onset of diabetes or not).

In [35]:
# create model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

#### 3. Compile Model

Now that the model is defined, we can compile it.

Compiling the model uses the efficient numerical libraries under the covers (the so-called backend) such as Theano or TensorFlow. The backend automatically chooses the best way to represent the network for training and making predictions to run on your hardware, such as CPU or GPU or even distributed.

When compiling, we must specify some additional properties required when training the network. Remember training a network means finding the best set of weights to make predictions for this problem.

We must specify the loss function to use to evaluate a set of weights, the optimizer used to search through different weights for the network and any optional metrics we would like to collect and report during training.

In this case, we will use **logarithmic** loss, which for a binary classification problem is defined in Keras as “**binary_crossentropy**“. We will also use the efficient gradient descent algorithm “**adam**” for no other reason that it is an efficient default. Learn more about the Adam optimization algorithm in the paper “Adam: A Method for Stochastic Optimization“.

Finally, because it is a classification problem, we will collect and report the classification accuracy as the metric.

In [36]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

#### 4. Fit Model

We have defined our model and compiled it ready for efficient computation.

Now it is time to execute the model on some data.

We can train or fit our model on our loaded data by calling the **fit()** function on the model.

The training process will run for a fixed number of iterations through the dataset called epochs, that we must specify using the **nepochs argument**. We can also set the number of instances that are evaluated before a weight update in the network is performed, called the batch size and set using the **batch_size** argument.

For this problem, we will run for a small number of iterations (150) and use a relatively small batch size of 10. Again, these can be chosen experimentally by trial and error.

In [48]:
# Fit the model
model.fit(X_train,Y_train, epochs=150, batch_size=10)


Epoch 1/150
614/614 [==============================] - 0s 385us/step - loss: 0.4843 - acc: 0.7557
Epoch 2/150
614/614 [==============================] - 0s 367us/step - loss: 0.4897 - acc: 0.7704
Epoch 3/150
614/614 [==============================] - 0s 373us/step - loss: 0.4825 - acc: 0.7736
Epoch 4/150
614/614 [==============================] - 0s 368us/step - loss: 0.4812 - acc: 0.7720
Epoch 5/150
614/614 [==============================] - 0s 406us/step - loss: 0.4726 - acc: 0.7736
Epoch 6/150
614/614 [==============================] - 0s 375us/step - loss: 0.4720 - acc: 0.7704
Epoch 7/150
614/614 [==============================] - 0s 366us/step - loss: 0.4873 - acc: 0.7769
Epoch 8/150
614/614 [==============================] - 0s 364us/step - loss: 0.4730 - acc: 0.7671
Epoch 9/150
614/614 [==============================] - 0s 403us/step - loss: 0.4702 - acc: 0.7736
Epoch 10/150
614/614 [==============================] - 0s 469us/step - loss: 0.4842 - acc: 0.7590
Epoch 11/150
614/61

#### 5. Evaluate Model

We have trained our neural network on the entire dataset and we can evaluate the performance of the network on the same dataset.

This will only give us an idea of how well we have modeled the dataset (e.g. train accuracy), but no idea of how well the algorithm might perform on new data. We have done this for simplicity, but ideally, you could separate your data into train and test datasets for training and evaluation of your model.

You can evaluate your model on your training dataset using the **evaluate()** function on your model and pass it the same input and output used to train the model.

This will generate a prediction for each input and output pair and collect scores, including the average loss and any metrics you have configured, such as accuracy.

In [52]:

# evaluate the model
scores = model.evaluate(X_validation, Y_validation)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

154/154 [==============================] - 0s 57us/step

acc: 77.92%


**Look for help on a library**

In [53]:
np_utils.to_categorical?

Signature: np_utils.to_categorical(y, num_classes=None)
Docstring:
Converts a class vector (integers) to binary class matrix.

E.g. for use with categorical_crossentropy.

# Arguments
    y: class vector to be converted into a matrix
        (integers from 0 to num_classes).
    num_classes: total number of classes.

# Returns
    A binary matrix representation of the input.
File:      ~/anaconda/lib/python3.5/site-packages/keras/utils/np_utils.py
Type:      function


In [39]:
Y.shape

(768,)

In [117]:
len(Y)

767

#### Prediction
Making predictions is as easy as calling model.predict(). We are using a sigmoid activation function on the output layer, so the predictions will be in the range between 0 and 1. We can easily convert them into a crisp binary prediction for this classification task by rounding them.

In [43]:
# calculate predictions
predictions = model.predict(X)
# round predictions
rounded = [round(x[0]) for x in predictions]
print(rounded[0:10])

[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0]


In [50]:
scores

[0.4729329448241692, 0.77922077844669291]